[
   {
      "id": 1,
      "author": "Rick Cook",
      "text": "Программирование сегодня — это гонка разработчиков программ..."
   },
   {
      "id": 2,
      "author": "Waldi Ravens",
      "text": "Программирование на С похоже на быстрые танцы на только..."
   },
   {
      "id": 3,
      "author": "Rick Cook",
      "text": "Программирование сегодня — это гонка разработчиков программ..."
   },
   {
      "id": 4,
      "author": "Waldi Ravens",
      "text": "Программирование на С похоже на быстрые танцы на только..."
   }
]